/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PTS.pts;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author Rodulfo R. Lopez
 */
public class PTS_MAIN_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form MakabuangNgaSystem2
     */
    public PTS_MAIN_LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Showpass_Box = new javax.swing.JCheckBox();
        Login_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Panel1.setBackground(new java.awt.Color(0, 132, 125));
        Panel1.setPreferredSize(new java.awt.Dimension(700, 400));
        Panel1.setLayout(null);
        Panel1.add(jLabel3);
        jLabel3.setBounds(500, 190, 0, 0);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(220, 227, 238));
        jLabel7.setText("<html><div style=\"text-align: center;\">\n    Don't have an account?<br />\n    Contact developer for assistance.\n</div><html/>");
        Panel1.add(jLabel7);
        jLabel7.setBounds(70, 260, 200, 70);

        email.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(220, 227, 238));
        email.setText("milwaukearrubio@gmail.com");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        Panel1.add(email);
        email.setBounds(70, 320, 200, 18);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(220, 227, 238));
        jLabel8.setText("PUBLIC");
        Panel1.add(jLabel8);
        jLabel8.setBounds(50, 110, 80, 40);

        jLabel9.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(220, 227, 238));
        jLabel9.setText("TRANSPORTATION");
        Panel1.add(jLabel9);
        jLabel9.setBounds(50, 130, 300, 45);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(220, 227, 238));
        jLabel6.setText("SYSTEM");
        Panel1.add(jLabel6);
        jLabel6.setBounds(280, 160, 70, 22);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 40, 40));
        jLabel1.setText("LOGIN ADMIN");

        Username.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Username.setName(""); // NOI18N
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("Password:");

        Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Showpass_Box.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        Showpass_Box.setForeground(new java.awt.Color(40, 40, 40));
        Showpass_Box.setText("Show Password");
        Showpass_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Showpass_BoxActionPerformed(evt);
            }
        });

        Login_button.setBackground(new java.awt.Color(102, 102, 102));
        Login_button.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        Login_button.setForeground(new java.awt.Color(220, 227, 238));
        Login_button.setText("log in admin");
        Login_button.setBorder(null);
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Showpass_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Showpass_Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Panel1.add(jPanel1);
        jPanel1.setBounds(360, 30, 310, 320);

        jButton1.setBackground(new java.awt.Color(220, 227, 238));
        jButton1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(40, 40, 40));
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel1.add(jButton1);
        jButton1.setBounds(10, 20, 30, 20);

        Dashboard_Button.setBackground(new java.awt.Color(102, 102, 102));
        Dashboard_Button.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        Dashboard_Button.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_Button.setText("USER DASHBOARD");
        Dashboard_Button.setBorder(null);
        Dashboard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_ButtonActionPerformed(evt);
            }
        });
        Panel1.add(Dashboard_Button);
        Dashboard_Button.setBounds(560, 360, 110, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonActionPerformed
        // TODO add your handling code here:
        String username, password, query;
        String SUrl, SUser, Spass;
        SUrl = "jdbc:MySQL://localhost:3306/admin_db";
        SUser = "root";
        Spass = "";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, Spass);
            if("".equals(Username.getText())){
                JOptionPane.showMessageDialog(new Jframe(),"Username is Require", "Error",  JOptionPane.ERROR_MESSAGE);
            }else if("".equals(Password.getText())){
                JOptionPane.showMessageDialog(new Jframe(),"Password is Require", "Error",  JOptionPane.ERROR_MESSAGE);
            }else{
                username = Username.getText();
                password = Password.getText();
                
                
                if(isAdmin(con, username, password)) {
                        PTS_NEW_ADMIN_DESIGN LoginFrame = new PTS_NEW_ADMIN_DESIGN();
                        LoginFrame.setVisible(true);
                        LoginFrame.pack();
                        LoginFrame.setLocationRelativeTo(null);
                        this.dispose();
                    
                }else{
                    JOptionPane.showMessageDialog(new Jframe(),"Account not found", "Error",  JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
            
        }catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
        
    }//GEN-LAST:event_Login_buttonActionPerformed

    
    private boolean isAdmin(Connection con, String email, String password) throws SQLException{
        String query = "SELECT username, password FROM admin WHERE username = ?";
        try (PreparedStatement stmt = con.prepareStatement(query)){
            stmt.setString(1, email);
            
            ResultSet rs = stmt.executeQuery();
            
            if(rs.next()){
                String Password = rs.getString("password");
                return password.equals(Password);
            }
            
            return false;
        }
    }
    
    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void Showpass_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Showpass_BoxActionPerformed
        if (Showpass_Box.isSelected()){
            Password.setEchoChar((char)0);   
        }else{
            Password.setEchoChar('*');
        }
        
    }//GEN-LAST:event_Showpass_BoxActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
    close();
    PTS_USER_DB Dashboard = new PTS_USER_DB();
    Dashboard.setVisible(true);
    Dashboard.pack();
    Dashboard.setLocationRelativeTo(null);
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit", "EXIT", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PTS_MAIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PTS_MAIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PTS_MAIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PTS_MAIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PTS_MAIN_LOGIN().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JButton Login_button;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JCheckBox Showpass_Box;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private static class Jframe extends Component {

        public Jframe() {
        }
    }

}
